// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsvbk0v39VWJAjbzdehELDF5SqouYgEUw',
    appId: '1:762448013773:web:214bde74938777284a3c84',
    messagingSenderId: '762448013773',
    projectId: 'cancer-vision-app',
    authDomain: 'cancer-vision-app.firebaseapp.com',
    databaseURL: 'https://cancer-vision-app-default-rtdb.firebaseio.com',
    storageBucket: 'cancer-vision-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVnOm1MJyWgPZ2fB9EOJs7UCmvND0bik8',
    appId: '1:762448013773:android:a7223081477619ca4a3c84',
    messagingSenderId: '762448013773',
    projectId: 'cancer-vision-app',
    databaseURL: 'https://cancer-vision-app-default-rtdb.firebaseio.com',
    storageBucket: 'cancer-vision-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD76OSbqxltVnHuKkJkOR31ibXLtiXW5lc',
    appId: '1:762448013773:ios:b0ba460ab0397a2f4a3c84',
    messagingSenderId: '762448013773',
    projectId: 'cancer-vision-app',
    databaseURL: 'https://cancer-vision-app-default-rtdb.firebaseio.com',
    storageBucket: 'cancer-vision-app.firebasestorage.app',
    androidClientId: '762448013773-00gcup5qrcups4dp2eooci781oat67ar.apps.googleusercontent.com',
    iosClientId: '762448013773-9212f144bav3jdnlvk6eci9js4rm9ksu.apps.googleusercontent.com',
    iosBundleId: 'com.example.cancervision',
  );
}
